### ISSUE TITLE
Code bytes to document and share on website

### ISSUE THREAD

**Issue by camilavargasp** [camilavargasp/camilavargasp.github.io#6]
Here, I'll be posting pieces of code that I think might be useful over and over again. With the hopes that at some point organize them into a page on my website

**Comment by camilavargasp** [comment]
**Code formatting in Quarto YAML**

```
---
title: "Using `sf` for Spatial Analysis & Intro to Making Maps"
title-block-banner: true
format:
  html: 
    code-link: true
    code-overflow: wrap
---
```
